In [2]:
import numpy as np

# Function to calculate Euclidean distance
def euclidean_distance(x, y):
    return np.sqrt(np.sum((x - y)**2))

# Function to calculate the neighborhood function
def neighborhood_function(distance, sigma):
    return np.exp(-distance**2 / (2 * sigma**2))

# Function to update weights
def update_weights(old_weight, target_weight, alpha, neighborhood_effect):
    return old_weight + alpha * neighborhood_effect * (target_weight - old_weight)

# Define parameters
alpha = 0.1
sigma = 2
target_neuron = (3, 3)
neighborhood_size = 2

# Initialize the SOM weights (assuming they are already converged)
som_weights = np.random.random((5, 5))

# Calculate the effect of the neighborhood function for each mode
for i in range(max(0, target_neuron[0] - neighborhood_size), min(5, target_neuron[0] + neighborhood_size + 1)):
    for j in range(max(0, target_neuron[1] - neighborhood_size), min(5, target_neuron[1] + neighborhood_size + 1)):
        distance = euclidean_distance(np.array([i, j]), np.array(target_neuron))
        neighborhood_effect = neighborhood_function(distance, sigma)
        som_weights[target_neuron[0], target_neuron[1]] = update_weights(
            som_weights[target_neuron[0], target_neuron[1]],
            som_weights[i, j],
            alpha,
            neighborhood_effect
        )

# Print the updated weights
print("Updated weights:")
print(som_weights)


Updated weights:
[[0.28863352 0.74224169 0.4322548  0.96053486 0.56875107]
 [0.42137561 0.11296762 0.17144606 0.00434254 0.47792316]
 [0.07344077 0.82594235 0.46414741 0.65923049 0.06806304]
 [0.58769323 0.91383354 0.81755066 0.41685572 0.28641238]
 [0.23149403 0.39156096 0.84377349 0.67293777 0.23693431]]
